[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
aws-config = "1.1.7"
aws-sdk-s3 = { version = "1.4.0", features = ["rt-tokio"] }
clap = { version = "4.5.47", features = ["derive"] }
tokio = { version = "1.38", features = ["full"] }
guid-create = "0.5"
