#!/usr/bin/env bash

echo "== deploy s3 bucket via cloudformation"

STACK_NAME="cfn-s3-simple2"

#"$(dirname "$0") is used to allow run scrip in any relative path

aws cloudformation deploy \
--template-file "$(dirname "$0")/template.yaml" \
--stack-name $STACK_NAME