#!/usr/bin/env bash

echo "sync"

set -e

if [ -z "$1" ]; then
  echo "Arg for bucket name is empty"
  exit 1
fi


BUCKET_NAME=$1

aws s3api list-objects-v2 \
--bucket $BUCKET_NAME \
--query Contents[].Key \
| jq -n '{Objects: [inputs | .[] | {Key: .}]}' > /tmp/delete_objects.json

aws s3api delete-objects --bucket $BUCKET_NAME --delete file:///tmp/delete_objects.json