#!/usr/bin/env bash

echo "== deleting s3 bucket"

if [ -z "$1" ]; then
  echo "Arg for bucket name is empty"
  exit 1
fi

BUCKET_NAME=$1
echo "Bucket name: $BUCKET_NAME"

aws s3api delete-bucket \
--bucket $BUCKET_NAME \

aws s3api list-buckets
